### ISSUE TITLE
no "ask question" input and avast and windows don't like it

### ISSUE THREAD

**Issue by JSJBDEV** [Rydion/Snapp#6]
Hello all!
Sorry to say, It's me again.

so I recently got my project to a stage where I am wanting some people to test the standalone version although I have a few problems:

the "ask question" block does not seem to do anything, (i have a debug "command line" and it does not execute anything after this block)

_there is no sound, I noticed this in an earlier issue however (I have background music)_
FIXED! see issue #3 

Avast and windows both seem to hate the exe file, windows doesn't trust it and i had to wait 10 minutes for avast to send it to there labs to scan it.

thank you as always for making a compiler for snapp.
~JSJBdev

**Comment by Rydion** [comment]
Hi, I'll look into the issue with the ask question block thingy as soon as I can.

As for the antivirus problem I myself haven't had any problems but then again I don't use Avast. I've heard it can be very picky. Usually this can be solved by submitting the exe to Avast for review but because every exe that's generated by Snapp! is a little bit different I don't know if that approach is going to work.

And last but not least, I myself haven't had any issues on my PC running Windows, but maybe it has something to do with security settings like Windows Defender, UAC or even the Windows version.

I'll investigate a little and try to see what can be done about those issues.

**Comment by JSJBDEV** [comment]
Thank you very much for looking into it :)

**Comment by Rydion** [comment]
Hi,
I'm sorry that it took so long for me to look into this but I've been busy as hell lately.

So, I just created a minimal project that uses the Ask and Wait block (I have attached it to this message) that does the following:

- Ask and wait
- Show the answer for 2 seconds

The windows executable version seems to work fine, if there is a problem it probably lies elsewhere.
Could you give me a little more information about the project and the OS for which you are trying to generate the standalone version?
[Test ask.zip](https://github.com/Rydion/Snapp/files/518344/Test.ask.zip)

**Comment by JSJBDEV** [comment]
I'm not at my usual computer currently but it is 64bit Windows and the box
for input showed up but when I typed into it nothing happened afterwards
Thanks
~JSJB

**Comment by Rydion** [comment]
Ok, I've also tested the windows 64bit version.

If I had to guess the problem probably lies in the blocks that handle the answer and not the Ask 'n' wait block itself.

**Comment by Rydion** [comment]
A new version of Snapp! has just been released that should get rid of the problem you described. As for Windows not linking the exe y don't think there's much I can do.
