### ISSUE TITLE
Build your own server

### ISSUE THREAD

**Issue by aidiken** [Rydion/Snapp#7]
Build your own server，upload Snapp-master，Why can't execute Build my app! ？

var url = 'http://app.maocode.com/web/index/index.html’

This link is correct ？

**Comment by Rydion** [comment]
Hi, in the index.js file you need to do the following. At the top of the file locate:

var url = 'http://yourdomain/gen_exec';

And rewrite it. In your case:

var url = 'http://app.maocode.com/gen_exec';

And to access the application just write **http://app.maocode.com** into your browser.

That is supposing that your server is set up in a way that http://app.maocode.com points to the instance of Node.js running Snapp*!*. The easiest way is to just let Node.js run on port 80 of the machine.

If you need any more help just let me know.

PS: Because this is quite a pain to do every time I'm currently working on a rewrite that will get rid of this and other issues.

**Comment by aidiken** [comment]
@Rydion Thank you
Now jump this, not open the window.
blob:http://mapp.maocode.com/0eaac743-3b0e-46dc-b458-06b64d067e9b
http://mapp.maocode.com/
 index.js     
var url = 'http://mapp.maocode.com';

**Comment by Rydion** [comment]
Hi the URL has to look exactly like:

var url = 'http://mapp.maocode.com/gen_exec';

with the **/gen_exec** part at the end.

**Comment by aidiken** [comment]
@Rydion 
var url = 'http://mapp.maocode.com/gen_exec';
http://mapp.maocode.com/
Still not successful
Cannot read file
Server port has been set to 80
What is the reason？
Thank you

**Comment by Rydion** [comment]
Hi,
I've taken a look at the page and the setup as far as Snapp*!* is concerned is correct. This seems to be some issue with how the server is set up. Are you running node directly on port 80 of the machine without anything in between like virtual machines, Apache, etc?
